---
- hosts: all
  become: yes
  tasks:
  - name: Update all package
    yum:
      name: '*'
      state: latest

  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Start httpd
    service: 
      name: httpd 
      state: started